# Generated by Django 4.2.5 on 2023-09-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
